before:
    hooks:
        - go mod download

changelog:
  sort: desc
  use: git
  filters:
    exclude:
    - Merge branch
    - Merge pull request

builds:
  - env:
        - CGO_ENABLED=0
    goos:
        - linux
        - windows
        - darwin
    goarch:
        - 386
        - amd64
        - arm64
    ignore:
        - goos: windows
          goarch: arm64
        - goos: darwin
          goarch: 386
    main: ./cmd
    binary: symfony
    ldflags: -s -w -X 'main.channel={{ if index .Env "AUTOUPDATE_CHANNEL" }}{{ .Env.AUTOUPDATE_CHANNEL }}{{ else }}dev{{ end }}' -X 'main.buildDate={{ .Date }}' -X 'main.version={{ .Version }}'
    flags:
        - -trimpath

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE

checksum:
    name_template: 'checksums.txt'

snapshot:
    name_template: "next"

universal_binaries:
    - replace: true

release:
  footer: |
    **Full Changelog**: https://github.com/symfony-cli/symfony-cli/compare/{{ .PreviousTag }}...{{ .Tag }}
